### PR TITLE
Fix library with current version of fmtlib (#66)

### PR DESCRIPTION
**Pull request by joonatoona**

### CODE REVIEW

**Comment by emilk** [comment]
I appreciate the effort, but please do not re-indent the entire library!

**Comment by joonatoona** [comment]
I'm sorry, I have no idea how that snuck in there. Stupid autoformatter :(

I've reset the indentaion back.

**Comment by Milerius** [comment]
any news ?

**Comment by joonatoona** [comment]
I _think_ I got them all? I don't see the difference in github, but `grep -c '^    ' loguru.{cpp,hpp}` shows that there's no space indents.

**Pull request merged**
