### PR TITLE
Enable Windows testing with AppVeyor CI

### PR DESCRIPTION
**Pull request by tusharpm**
I was able to make the tests run (and pass 😃) by modifying some pieces in the test directory.
I kept the bash scripts with the minimal changes required to keep them up to date.

The complete test suite can now be run using just one command line (across platforms) - just CMake instead of bash. The command is available in the AppVeyor configuration in the test_script section.
Please enable the AppVeyor integration and the Github hooks to facilitate running the CI tests on all commits/PRs.

### CODE REVIEW

**Comment by tusharpm** [comment]
Forgot to mention in the description: a sample AppVeyor build (from my fork) is available at https://ci.appveyor.com/project/tusharpm/loguru.

**Comment by emilk** [comment]
I have never used AppVeyor but I will just trust you on this one and see what happens. Here we go!

**Comment by emilk** [comment]
That worked great - thanks for the contribution, @tusharpm !

**Comment by tusharpm** [comment]
My pleasure!

**Pull request merged**
