### PR TITLE
Enable thread naming on Windows

### PR DESCRIPTION
**Pull request by justinian**
* Add a `LOGURU_WINTHREADS` macro, defined when on MSVC or Cygwin
* Thread names stored as a TLS static char array in `get_thread_name_win32`

### CODE REVIEW

**Comment by emilk** [comment]
Cool! Have you considered doing it this way: https://msdn.microsoft.com/en-us/library/xcb2z8hs.aspx ?  The advantage is, I guess, that then the thread name in Loguru and your favorite debugger will match.

**Comment by justinian** [comment]
Unfortunately, that method only works when there's a debugger attached, because the structures it updates live in debugger memory, not in your own process. Why they chose to go that route instead of TLS so that it'd be more universally useful... ¯\_(ツ)_/¯

**Comment by justinian** [comment]
There's also `SetThreadDescription` which seems to solve that issue, but requires at least Windows 10 Creators Update or Server 2016, which I thought might be a little restrictive to users of the library.

**Comment by emilk** [comment]
Ok, thanks @justinian !

**Pull request merged**
